### ISSUE TITLE
Regex doesn't work in Firefox

### ISSUE THREAD

**Issue by retorquere** [BridgeAR/safe-stable-stringify#26]
```
const strEscapeSequencesRegExp = /[\u0000-\u001f\u0022\u005c\ud800-\udfff]|[\ud800-\udbff](?![\udc00-\udfff])|(?<![\ud800-\udbff])[\udc00-\udfff]/
```

yields

```
invalid regexp group
```

in firefox. This has been added in the recent release of this package I think, because the error started appearing since I upgraded.

**Comment by BridgeAR** [comment]
@retorquere thanks, that was indeed a non-intentional breaking change. I tried to come up with a regular expression for older browsers that do not yet support negative lookbehind but I could not yet find one that really matches the case. I might add a feature detection to make sure it works for older browsers but in that case some characters might not be escaped or I could use the manual implementation which is slower for bigger input values.
